### ISSUE TITLE
Export methods and AC analysis do not use latest iteration

### ISSUE THREAD

**Issue by svenboulanger** [svenboulanger/SpiceSharp#7]
Most devices will use `state.OldSolution` or the last state variable in `state.States[0]` (which are solutions to the previous iteration) as opposed to`state. Solution` (the solution of the current iteration) to calculate small-signal parameters for AC analysis. I believe this is not logical, as the most recent iteration should be a better approximation to the real solution.
The same happens for a lot of extract methods of devices.

Note that changing this breaks tests, because Spice 3f5, which is used as a reference, does this as well. I do not think other Spice-derivatives will have changed this (from what I could see ngSpice didn't).

**Comment by svenboulanger** [comment]
One way of resolving this is simulating using Spice 3f5 with very strict tolerances. This way we get something very close to the "true" solution of the model, and the differences how Spice# solves it become less important, as long as it is correct (ie. within tolerance levels to this "true" solution).

**Comment by CIVITAS-John** [comment]
Maybe you can add a setting option about it, like 'Spice 3f5 Compatible' and 'Something Greater'. lol

**Comment by svenboulanger** [comment]
Adding a settings flag for some kind of legacy mode would make sense for a Spice clone, however that is not the direction I'd like Spice# to take. I'd like to improve upon it. I believe the main concern should be that the models and simulations lead to accurate results.

**Comment by svenboulanger** [comment]
Using strict tolerances works for DC analysis, but still needs some work for AC, Transient and Noise analysis. Maybe it's better to test the model behaviors separately. I'll look into what's possible.

**Comment by svenboulanger** [comment]
We modified Spice 3f5 a little bit such that it uses the last iteration instead.
I am convinced that it is a bug in Spice 3f5, especially after finding some code that **does** use the last iteration.
Please note that none of the simulation results will deviate significantly because that is the nature of the iterative method.
